#以下配置项除 User_Cookie 、Appoint_Up 、Coin_Number以外默认空白就是True,不执行填写False即可

User_Cookie: #用户Cookie
  - "你的Cookie"
  - "第二个Cookie"

Work_Cookie: #是否运行脚本
  -

Day_Task: #是否执行每日任务
  -
  - false

Appoint_Up: # 是否指定uid
  - ["456664753", "431073645"]
  -  #第二个Cookie此处空白即使用随机视频

Put_Coin: #是否投币
  -
  - false

Coin_Number: # 单个视频投币数量(空白即为1)
  -

Exchange_Coin: # 是否兑换银瓜子
  -
